### ISSUE TITLE
It wont compile

### ISSUE THREAD

**Issue by Enovale** [luigigamer55/luigi#2]
I ran `make` and it gives me 

```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
at org.multimc.EntryPoint.listen(EntryPoint.java:143)
at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
at net.minecraft.launchwrapper.Launch.(Launch.java:34)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
... 8 more
Exiting with -1
进程退出，代码：-1。
```

Do you have any suggestion?

**Comment by CorneliusCornbread** [comment]
![luigi ballin](https://user-images.githubusercontent.com/8294697/103732971-3d859300-4fae-11eb-8d57-ca53d4eba751.gif)

**Comment by Enovale** [comment]
![luigi](https://user-images.githubusercontent.com/17408285/103732989-48d8be80-4fae-11eb-9f55-53247eb2ed00.gif)
